name: Testing libcobblersignatures

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**.py'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the tests
      run: |
        pytest --cache-clear --cov=libcobblersignatures tests/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: 53b8444a-0631-40e8-a199-7c5d71a8d174
        flags: unittests
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        verbose: true
